# Generated by Django 5.2.13 on 2026-04-17 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osteo_core', '0002_horse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField()),
                ('reason_for_visit', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='osteo_core.horse')),
            ],
        ),
    ]
