# Generated by Django 5.2.13 on 2026-04-24 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osteo_core', '0005_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_performed', models.DateTimeField(auto_now_add=True)),
                ('assessment_data', models.JSONField(default=dict)),
                ('general_notes', models.TextField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='osteo_core.appointment')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='osteo_core.horse')),
            ],
        ),
    ]
